# Generated by Django 6.0.1 on 2026-01-11 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug_type', models.CharField(choices=[('UI', 'UI / Visual'), ('FUNCTIONALITY', 'Functionality / Broken Feature'), ('SECURITY', 'Security Vulnerability')], max_length=50)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalityBug',
            fields=[
                ('bug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugs.bug')),
                ('affected_module', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_result', models.TextField(blank=True, null=True)),
                ('actual_result', models.TextField(blank=True, null=True)),
                ('reproduction_steps', models.TextField(blank=True, null=True)),
            ],
            bases=('bugs.bug',),
        ),
        migrations.CreateModel(
            name='SecurityBug',
            fields=[
                ('bug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugs.bug')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('impact_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('confidentiality_impact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('bugs.bug',),
        ),
        migrations.CreateModel(
            name='UIBug',
            fields=[
                ('bug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bugs.bug')),
                ('browser_name', models.CharField(max_length=100)),
                ('browser_version', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('screen_resolution', models.CharField(max_length=50)),
            ],
            bases=('bugs.bug',),
        ),
    ]
