# Generated by Django 6.0.1 on 2026-01-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='functionalitybug',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='securitybug',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uibug',
            options={'managed': False},
        ),
    ]
